Webshop/Week 4,5,6/WebshopEF/WebshopEF/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebshopEF.Helper;
using WebshopEF.Models;
using WebshopEF.BusinessLayer.Services;

namespace WebshopEF.Controllers
{
    public class BasketController : Controller
    {
        private IDeviceService ds = null;
        private IBasketService bs = null;

        public BasketController(IDeviceService ds,IBasketService bs)
        {
            this.ds = ds;
            this.bs = bs;
        }

        [Authorize]
        [HttpGet]
        public ActionResult Index()
        {
            string user = User.Identity.Name;
            List<Basket>items = bs.GetBasketItems(user);

            PriceCalculator calculator = new PriceCalculator(items);
            ViewBag.TotalePrijs = calculator.BerekenPrijs();

            return View(items);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Add(int? id)
        {
            if (!id.HasValue)
                return RedirectToAction("Index");
            Device d = new Device();
            d = ds.GetDeviceById(id.Value);

            return View(d);
        }

        [HttpPost]
        public ActionResult Add(int? id, int? number)
        {
            if (!id.HasValue || !number.HasValue || number.Value == 0)
                return RedirectToAction("Index", "Device");

            Basket b = new Basket();
            b.Aantal = number.Value;
            b.Timestamp = DateTime.Now;
            b.User = User.Identity.Name;
            b.Device = ds.GetDeviceById(id.Value);
            bs.AddItemToBasket(b);

            return RedirectToAction("Index");
        }

        

        public int ItemsInBasket()
        {
            return bs.GetBasketItems(User.Identity.Name).Count;
        }
    }
}

Webshop/Week 4,5,6/WebshopEF/WebshopEF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("IoT Shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cataloog", "Index", "Device")</li>
                        @if (User.Identity.IsAuthenticated)
                        {
                        <li>@Html.ActionLink("Nieuw", "Create", "Device")</li>
                        <li><a href="/Basket">Basket (@Html.Action("ItemsInBasket", "Basket"))</a></li>
                        }
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Jim Butseraen</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>