Webshop/Week 4,5,6/WebshopEF/WebshopEF/Controllers/DeviceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebshopEF.Models;
using WebshopEF.PresentationModels;
using WebshopEF.Repositories;
using WebshopEF.BusinessLayer.Services;

namespace WebshopEF.Controllers
{
    public class DeviceController : Controller
    {
        private IDeviceService ds;

        public DeviceController(IDeviceService ds)
        {
            this.ds = ds;
        }

        [HttpGet]
        public ActionResult Index()
        {
            List<Device> devices = new List<Device>();
            devices = ds.GetDevices();
            return View(devices);
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (!id.HasValue)
                return RedirectToAction("Index");

            Device device = new Device();
            device = ds.GetDeviceById(id.Value);
            return View(device);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            CreatePM pm = new CreatePM();

            pm.OperatingSystems = new SelectList(ds.GetOperatingSystems(), "ID", "Name");
            pm.Frameworks = new SelectList(ds.GetFrameworks(), "ID", "Name");
            pm.SelectedOperatingSystems = new SelectList(new List<OS>(), "ID", "Name");
            pm.SelectedFrameworks = new SelectList(new List<Framework>(), "ID", "Name");
            pm.Device = new Device();

            return View(pm);
        }

        [HttpPost]
        public ActionResult Create(CreatePM createPM)
        {
            createPM.OperatingSystems = new SelectList(ds.GetOperatingSystems(), "ID", "Name");
            createPM.Frameworks = new SelectList(ds.GetFrameworks(), "ID", "Name");
            bool canComplete = false;

            switch(createPM.submit)
            {
                case "Next":
                    canComplete = true;
                    break;
                case "Add OS":
                    createPM.idsOS += createPM.OperatingSystemId.ToString()+";";
                    break;
                case "Add FR":
                    createPM.idsFR += createPM.FrameworkId.ToString()+";";
                    break;        
            }

            List<OS> OperatingSystems = CreateSelectedOS(createPM.idsOS);
            List<Framework> Frameworks = CreateSelectedFR(createPM.idsFR);

            if(Frameworks.Count!=0)createPM.SelectedFrameworks = new SelectList(Frameworks,"ID","Name");
            else createPM.SelectedFrameworks = new SelectList(new List<Framework>(),"ID","Name");

            if(OperatingSystems.Count!=0)createPM.SelectedOperatingSystems = new SelectList(OperatingSystems,"ID","Name");
            else createPM.SelectedOperatingSystems = new SelectList(new List<OperatingSystem>(),"ID","Name");

            if (ValidateForm(createPM))
            {
                if(canComplete)
                {
                    HttpPostedFileBase photo = createPM.Upload;
                    Device d = new Device();
                    d = createPM.Device;

                    if (createPM.Upload != null)
                    {
                        if (photo.ContentLength > 0)
                        {
                            ds.SaveImage(photo);
                            d.Picture = photo.FileName;
                        }
                    }

                    d.Frameworks = Frameworks;
                    d.OperatingSystems = OperatingSystems;
                    ds.CreateDevice(d);
                    return RedirectToAction("Index");
                }               
            }
            else
            {
                createPM.Error = "Complete all fields!";
            }
            return View(createPM);
        }

        public bool ValidateForm(CreatePM pm)
        {
            if (pm.Device.Price < 1) return false;
            if (pm.Device.RentPrice < 1) return false;
            if (pm.Device.Stock < 1) return false;
            if (pm.SelectedFrameworks.Count() < 1) return false;
            if (pm.SelectedOperatingSystems.Count() < 1) return false;
            return true;
        }
        public List<OS> CreateSelectedOS(string ids)
        {
            List<OS> list = new List<OS>();

            if (ids != null)
            {
                string[] items = ids.Split(';');

                foreach (string item in items)
                {
                    if (item != "")
                    {
                        list.Add(ds.GetOperatingSystemById(Convert.ToInt32(item)));
                    }
                }
            }

            return list;
        }
        public List<Framework> CreateSelectedFR(string ids)
        {
            List<Framework> list = new List<Framework>();

            if (ids != null)
            {
                string[] items = ids.Split(';');

                foreach (string item in items)
                {
                    if (item != "")
                    {
                        list.Add(ds.GetFrameworkById(Convert.ToInt32(item)));
                    }
                }
            }
            return list;
        }
    }
}

Webshop/Week 4,5,6/WebshopEF/WebshopEF/Views/Device/Create.cshtml
@model WebshopEF.PresentationModels.CreatePM

@using (Html.BeginForm("Create", "Device", FormMethod.Post, new { @class = "form-actions", @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-6">
            <h2>New device</h2>
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Device.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Device.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Device.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Device.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Device.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Device.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Device.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Device.Price, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Device.Price, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Device.RentPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Device.RentPrice, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Device.RentPrice, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Device.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Device.Stock, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Device.Stock, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label for="Upload" class="control-label col-md-2">Photo:</label>
                    <div class="col-md-10">
                        <input type="file" name="Upload" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Next" class="btn btn-primary" name="submit" />
                    </div>
                </div>
                <p class="error">@Model.Error</p>
            </div>
        </div>
        <div class="col-md-6">
            <h2>Select software</h2>
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.OperatingSystems)
                    </div>
                    <div class="col-md-5">
                        @Html.DropDownListFor(model => model.OperatingSystemId, Model.OperatingSystems, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.OperatingSystems, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-5">
                        <input type="submit" value="Add OS" class="btn btn-primary" name="submit" style="margin-top:15px" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.SelectedOperatingSystems)
                    </div>
                    <div class="col-md-5">
                        @Html.ListBox("SelectedOperatingSystems", Model.SelectedOperatingSystems)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.Frameworks)
                    </div>
                    <div class="col-md-5">
                        @Html.DropDownListFor(model => model.FrameworkId, Model.Frameworks, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.OperatingSystems, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-5">
                        <input type="submit" value="Add FR" class="btn btn-primary" name="submit" style="margin-top:15px" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.SelectedFrameworks)
                    </div>
                    <div class="col-md-5">
                        @Html.ListBox("SelectedFrameworks", Model.SelectedFrameworks)
                    </div>
                </div>
                <input type="hidden" name="idsOS" value="@Model.idsOS" />
                <input type="hidden" name="idsFR" value="@Model.idsFR" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Webshop/Week 4,5,6/WebshopEF/WebshopEF/Views/Device/Details.cshtml
@model WebshopEF.Models.Device
<div class="row">
    <div class="col-md-4">
        <h2>@Model.Name.Split('-')[0]</h2>
        <p>
            <img src="http://webshopef.blob.core.windows.net/images/@Model.Picture"/>
        </p>
        <p><b>Model</b>:@Model.Name</p>
        <p><b>Huur mij voor</b>: &euro; @Model.RentPrice</p>
        <p><b>Stock te verhuren</b>: @Model.Stock</p>
        <br />
        <a href="/Device/Index" class="btn btn-primary">Go back</a>
    </div>
</div>

Webshop/Week 4,5,6/WebshopEF/WebshopEF/Views/Device/Index.cshtml
@model IEnumerable<WebshopEF.Models.Device>
<a href="/Device/Create" class="btn btn-success">Create</a>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4">
            <h2>@item.Name.Split('-')[0]</h2>
            <p>@item.Description</p>
            <a href="/Device/Details/@item.ID" class="btn btn-primary">Details</a>
            <a href="/Basket/Add/@item.ID" class="btn btn-primary">Add Item</a>
        </div>
    }
</div>